import type { IncomingMessage } from 'node:http';
import { HttpError } from './auth.js';

export const MAX_BODY_BYTES = 32_768;
export async function jsonBody(request: IncomingMessage): Promise<Record<string, unknown>> { const chunks: Buffer[]=[]; let size=0; for await (const chunk of request) { const buffer=Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk); size+=buffer.length; if(size>MAX_BODY_BYTES) throw new HttpError(413,'Requisição muito grande.'); chunks.push(buffer); } try { const result=JSON.parse(Buffer.concat(chunks).toString('utf8')); if (!result || typeof result !== 'object' || Array.isArray(result)) throw new Error(); return result as Record<string,unknown>; } catch { throw new HttpError(400,'Corpo da requisição inválido.'); } }
export function uuid(value: unknown, label = 'Identificador'): string { if(typeof value !== 'string'||!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)) throw new HttpError(400,`${label} inválido.`); return value; }
export function text(value: unknown, label: string, max: number, required = true): string | undefined { if(value == null && !required) return undefined; if(typeof value !== 'string') throw new HttpError(400,`${label} inválido.`); const normalized=value.trim(); if((required&&!normalized)||normalized.length>max) throw new HttpError(400,`${label} inválido.`); return normalized; }
export function isoDate(value: unknown, label: string): string { if(typeof value !== 'string'||Number.isNaN(Date.parse(value))) throw new HttpError(400,`${label} inválida.`); return new Date(value).toISOString(); }
export function pagination(url: string | undefined): { limit:number; offset:number } { const q=new URL(url ?? '/', 'http://localhost').searchParams; const limit=Math.min(Math.max(Number(q.get('limit') ?? 30),1),100); const offset=Math.max(Number(q.get('offset') ?? 0),0); if(!Number.isInteger(limit)||!Number.isInteger(offset)) throw new HttpError(400,'Paginação inválida.'); return {limit,offset}; }
